import { Animal } from '../home/Model/Animal';

export const dogs: Animal[] = [
  {
    id: 20,
    img: 'http://img.boqiicdn.com/Data/BK/P/img45551405674702.jpg',
    title: '哈士奇',
    desc: '',
    detail: '',
    tag: '二哈',
  },
  {
    id: 21,
    img: 'http://img.boqiicdn.com/Data/BK/P/img76411410941452.jpg',
    title: '金毛',
    desc: '',
    detail: '',
    tag: '暖男',
  },
  {
    id: 22,
    img: 'http://img.boqiicdn.com/Data/BK/P/imagick53831435572176.png',
    title: '博美',
    desc: '',
    detail: '',
    tag: '',
  },
  {
    id: 23,
    img: 'http://img.boqiicdn.com/Data/BK/P/img18631410861140.jpg',
    title: '柴犬',
    desc: '',
    detail: '',
    tag: '',
  },
  {
    id: 24,
    img: 'http://img.boqiicdn.com/Data/BK/P/img99521410942868.jpg',
    title: '贵宾犬',
    desc: '',
    detail: '',
    tag: '',
  },
  {
    id: 25,
    img: 'http://img.boqiicdn.com/Data/BK/P/img89351410944114.jpg',
    title: '泰迪',
    desc: '',
    detail: '',
    tag: '',
  },
  {
    id: 26,
    img: 'http://img.boqiicdn.com/Data/BK/P/img14771410943900.jpg',
    title: '萨摩耶 ',
    desc: '',
    detail: '',
    tag: '',
  },
  {
    id: 27,
    img: 'http://img.boqiicdn.com/Data/BK/P/img62631410858909.jpg',
    title: '拉布拉多',
    desc: '',
    detail: '',
    tag: '搜救犬',
  },
  {
    id: 28,
    img: 'http://img.boqiicdn.com/Data/BK/P/img55631410860146.jpg',
    title: '巴哥',
    desc: '',
    detail: '',
    tag: '短腿',
  },
];
